set nocompatible
filetype off 

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-commentary'
Plug 'w0rp/ale'
call plug#end()

filetype plugin indent on
set number

" Fix for backspace in insert mode on macOS
set backspace=indent,eol,start

let g:ale_fixers = {'javascript': ['prettier_standard'], 'python': ['black']}
let g:ale_linters = {'javascript': [''], 'python': ['flake8']}
let g:ale_fix_on_save = 1
