set nocompatible
filetype off 

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-commentary'
Plugin 'majutsushi/tagbar'
Plugin 'tpope/vim-fugitive'
Plugin 'w0rp/ale'
Plugin 'davidhalter/jedi-vim'
Plugin 'plytophogy/vim-virtualenv'
Plugin 'fatih/vim-go'
call vundle#end()

filetype plugin indent on
set number

" Fix for backspace in insert mode on macOS
set backspace=indent,eol,start

let g:virtualenv_auto_activate = 1 
let g:ale_python_pylint_options = '--load-plugins pylint_django'
