set nocompatible
filetype off 

call plug#begin('~/.vim/plugged')

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf.vim'
call plug#end()

filetype plugin indent on
set number

" Fix for backspace in insert mode on macOS
set backspace=indent,eol,start
