# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

COMPLETION_WAITING_DOTS="true"
CASE_SENSITIVE="true"

source $ZSH/oh-my-zsh.sh

bindkey -v
bindkey "^?" backward-delete-char

unsetopt correct_all
unsetopt share_history

# Put homebrew tools first on path
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.scripts

# Set commonly used variables
export LANG=en_US.UTF-8
export EDITOR=vim

# direnv hook
eval "$(direnv hook zsh)"

# Use ipdb when available for python breakpoint debugging
export PYTHONBREAKPOINT=ipdb.set_trace

# Use 1Password SSH agent
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
